### ISSUE TITLE
hl_plplot17e: runtime error

### ISSUE THREAD

**Issue by vmagnin** [jerryd/gtk-fortran#96]
The hl_plplot17e and plplot17e_gto examples compile but execution fail, since (at least) gtk-fortran 16.04.gtk3.18.9. This problem concerns only the gtk3 branch. Everything is OK with GTK 2 (master branch).

``` bash
./hl_plplot17e
hl_plplot17e: ../../../../src/cairo-surface.c:928: cairo_surface_reference: Assertion `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' failed.
Program received signal SIGABRT: Process abort signal.
Backtrace for this error:
#0  0x7FBCFD815E08
#1  0x7FBCFD814F90
#2  0x7FBCFD15D49F
#3  0x7FBCFD15D418
#4  0x7FBCFD15F019
#5  0x7FBCFD155BD6
#6  0x7FBCFD155C81
#7  0x7FBCFF38B16F
#8  0x7FBCFF34A1A4
#9  0x7FBCFF33D6F1
#10  0x7FBCF2356566
#11  0x7FBCFDF625F3
#12  0x7FBCFDF641B5
#13  0x7FBCFDF73BBB
#14  0x7FBCFDF74456
#15  0x7FBCFDF745C5
#16  0x7FBCFDF74891
#17  0x7FBCFDF81018
#18  0x4037D0 in __plplot_code_ex17_MOD_add_point
#19  0x403E05 in MAIN__ at hl_plplot17e.f90:?
Abandon (core dumped)
```

**Comment by vmagnin** [comment]
The hl_plplot17e and plplot17e_gto examples compile and run OK with:
GTK+ 3.22.25, GLib 2.54.1,  Ubuntu 17.10 x86_64, Python 3.6.3
